apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ENV: {{ .Values.config.ENV }}
  OWNER: {{ .Values.config.OWNER }}
  index.html: |
{{ .Values.html.index | indent 4 }}
